### ISSUE TITLE
Can't make mount point

### ISSUE THREAD

**Issue by mobilelifeful** [sentinm/Rclone-Heroku#2]
Thank you for sharing this, 
but it seems like can't make mount point at this time. (Can you please confirm if true).

**Comment by sentinm** [comment]
Can you send a screenshot of the logs mentioning the error

###### _sorry for the late reply xd_

**Comment by bolavefasfas** [comment]
I guess you need to give permission for **fuse mount** to docker container to be able to do that 

```
version: "3.7"
services:
  rclone:
    image: rclone/rclone
    container_name: rclone
    restart: unless-stopped
    volumes:
      - /mount/dir:/mount/dir
      - /etc/fuse.conf:/etc/fuse.conf
      - /root/config:/config/rclone
      - /root/rclone/log:/log
      - /root/rclone/cache:/cache
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    command: 'rcd --rc-web-gui --rc-web-gui-no-open-browser --rc-addr 0.0.0.0:$PORT --rc-user $USERNAME --rc-pass $PASSWORD '   
```

add this is your compose file to be able to mount it not tested just speculating 
and you cant mount on heroku or other free services to be able to do that you need own server or vps where you have sudo access 

Let me know if this works 

References 
1.https://forum.rclone.org/t/docker-compose-rclone-data-mount-not-accessible-on-host/29419/6
2.https://forum.rclone.org/t/it-is-possible-to-run-rclone-inside-the-docker-container-and-mount-the-folder-to-host/31268/6
